repository pattern and add student with course selected
hamzaaslam76/interanTaskOneAndTwo pull request #3
Opened 2020-10-05 05:23 UTC by hamzaaslam76

2020-10-05 08:21 UTC, Shanfiaz commented on StudentApplication/Repository/Repository/StudentRepositoryP.cs
> +
Remove the extra spacings

2020-10-05 08:21 UTC, Shanfiaz commented on StudentApplication/Repository/Repository/StudentRepositoryP.cs
> +
Why empty?????

2020-10-05 08:21 UTC, Shanfiaz commented on StudentApplication/Repository/Repository/_IAllRepository.cs
> +        void    Save();
remove the spac between void and save

2020-10-05 08:21 UTC, Shanfiaz commented on StudentApplication/WebApi/Controllers/StudentsController.cs
> +
remove spacings

2020-10-05 08:21 UTC, Shanfiaz commented on StudentApplication/WebApi/Controllers/StudentsController.cs
> +
Remove spaces

2020-10-05 08:21 UTC, Shanfiaz commented on StudentApplication/WebApi/Controllers/StudentsController.cs
> +            var Item = _studentRepositoryp.GetModelById(id);
var Item name is in pascal case, it should be camel case

2020-10-05 08:21 UTC, Shanfiaz commented on script/WebApiShowTable.js
> +
remove extra spacings

2020-10-05 08:21 UTC, Shanfiaz commented on script/WebApiShowTable.js
> +    debugger;
remove debuggers

2020-10-05 09:06 UTC, Nauman7 requested changes

2020-10-05 09:06 UTC, Nauman7 commented on StudentApplication/Repository/Repository/StudentRepositoryP.cs
> +                        DbContext.SaveChanges();
move this savechanges outside the foreach loop

2020-10-05 09:06 UTC, Nauman7 commented on StudentApplication/Repository/Repository/StudentRepositoryP.cs
> +
why not using the RepositoryBase Method? it seems empty model in select

2020-10-05 09:06 UTC, Nauman7 commented on StudentApplication/WebApi/Controllers/StudentsController.cs
> +                var item = _studentRepositoryp.GetModel();
make it in one line
`return itme==null?Ok("No Record In Table"):Ok(item) `

2020-10-05 09:06 UTC, Nauman7 commented on StudentApplication/WebApi/Controllers/StudentsController.cs
> +            //if(item == true)
remove commented code

2020-10-05 09:06 UTC, Nauman7 commented on WebApiStudent.html
> +
why empty lines ???

2020-10-05 09:06 UTC, Nauman7 commented on script/WebApiShowTable.js
> +               if(data == true)
if(data) is enough

2020-10-06 12:15 UTC, merged

2020-10-06 12:17 UTC, hamzaaslam76 commented on StudentApplication/Repository/Repository/StudentRepositoryP.cs
> +
OK